const express = require('express')
const router = express.Router()
const user = require('./modules/user')
const admin = require('./modules/admin')
const exhibition=require('./modules/exhibition')
const collection=require('./modules/collection')
const video=require('./modules/video')
const cart=require('./modules/cart')
const ticket=require('./modules/ticket')
const { apiErrorHandler } = require('../middleware/error-handler')

router.use('/users', user)
router.use('/admin', admin)
router.use('/exhibitions',exhibition)
router.use('/collections',collection)
router.use('/videos',video)
router.use('/carts',cart)
router.use('/ticket',ticket)
router.use('/', apiErrorHandler)

module.exports = router